---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: daddy
spec:
  encryptedData:
    .dockerconfigjson: AgBkXwYVp8sX0CxDgjVUtbM5sSk+Sgw4HxNt/RQKg4p8pUUew2LPuvgVa4QsXMTNE/+MFv7E9urE5KJMEJQrCXjV2a7RcGAqph1jMfgL8WO3XdLAgDXY/MBepiPWravfhau/Mnrlm+rmHw6hrzacLbevI5JE2p1kEZbmqLghriSkFesOnSizWwVU6bFnA+Euwsv9nJC9rg9+6IMaBAezh48HuoVKSiSE9HHxCannBbrBFu9k0E7dYVW2zwYGg1jFFw9PcP5/X0l4OgE9UTTmBPCvSwx+7Zbb7VWoLJYjRla8pPgoX0fNudhQKTPUdtu1G2FiGqo0KRbuoOzBaOG0/z0bqpdAHx3A6SpTi2wuKpMwfAVPu5wX7lu01D5h3HG3rJa1r/G3EKAkYYgf6cXijr0wTpFGxzwVZRLD2IAEfiHtBHihuRRcZbNrMKOKA4EaGQFZpwiux7Oz0YqQanznn5DEdUFTh6AipXl58Ej7rYGlcKLGFtRZU1svv2F5ZQNQy0KjZ9kpFzhHkdNOxawQm7TH0GOSoqx1f3gdwJuQbP4Le0EvIaV5xZUwH4Uouu5ZLt2/jKi9OUy0bYAW+l0PZm5ehIdCqF38xl/UBzfhgaPAF27Y0gTrEpnNCeXfFEBH5Y+P8Ok6TVatJAj6/JaB/0zsACZvPUfzC9L4KFdoqORnsjtjB8nBDXerEdAAMx6mjNyUQsmP/oQkgX/zVHlH6fntQeEMwGltncRhMQow6WV8YawfloDDyT3Y7fCpBDOLcyUAX2zyn/C0a2dUHW/GW7Pt3nGixAJMqnf52k6rhi7UlSMiNv6HNeU5STnnur3eWdEbg1B8HTsfkfTyiG+wqbVImRJ0nAlEHf8g0+ptc1W8SFUf7PpST9pmlcDUmsXrnsl3Sj5596zClTF4K/UxFZ3ohv5jYC3PMTpj9fg6Cem09YJWVtfKxNoO+g==
  template:
    metadata:
      name: ghcr-credentials
      namespace: daddy
    type: kubernetes.io/dockerconfigjson
