---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daddy-github-oauth-secret
  namespace: daddy
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgCCI3vCOqyy3Gtm4ifw9SsRQKSLu4rx8TBZbYry3rB+uo6cRj/fbPrM+6BW1CwsHvlswxIvLem2dea3Ov6KKbyHWChcnQ1SlICqxK8x2i8NOsCw+Kjb/8mMoMHpDQSKOyZwYsol+GzvuI0/C4JW5csMiG8u9k/WwitmlKMJ/TujPuQ9Fs+cAUZ5fC/8WE3r2FXH+46zKJirU77EHYK/N+ZkZTkBBKRocR06YMozBlP+NU2YY3ZnbX0Ju8Z0CRKy9A5IOd+fXgxNiEUQuq03rV96K8e3Uo28BMei6YFBMNj3ak47Lu31cuvuBUb4llftfZFBPXLHL9x2QgfVIG57p6RdzxtBWsJGWmYd0qCJ8Na13a2N6qHSEd6VD3Fz12ITLBrp2XnZpINEpUIreA+aP4X9SXPtx51n5HkZuIFnlkkBF72BuKOnOGA7pK6OmDWN5q3R6S3I0D4QveBCfChzlnnPwvkB6oOh+GvafbY7M8K0gwzlexpg/VY36b+dwkBmrPTzEs3vrZTYWZZgwUDquj8v5x6YB5Hv1jxVncJtzyLApD6V4qrIGPYOQvGpfk3yC4nxG8LLli3KpxU7x6QRiarCpKt7GrOKV9kCoedmoHR53RZmlAH+BB4CQWgQCJ0aEASIasY4BcXXEeW7ovv8bBMIMKmQMOPD5jgJSXVO0BLb+bgH8AfhWVOBk2GI97rBT9MEGgclGWFnfhGr6Zp8E5D2/aNtPA==
    GITHUB_CLIENT_SECRET: AgA87mmx/jc35RJUYM6i8i1KF7Hv9tpnR2v1WRYjzo7DBh5g5ua9egi+y1/Ywn2hnSpdGrwarX3TYW4QBUIKF7bxY6q+RAAKYkAMr0fcTRv4B2eZTGUJO9X0wmyoVdDC5K60Zb3u7+ikObtPkGoCjfpIdj4+7r2qGHx7x/HCxcIBaxIyKvlTN/181Q0ITK9MHVadouXoeOvwQAbalMM7NDdZIMggEDIIhY8G61Hqp8Af+aTxPaPoLSImmhSRCxUQ73l5NFO63AXQTebcdgpSJs3R7t8cnUbTDgFHy80xzFsp6C/ZgmYqlOFIKUYXwAX3XHJWQ9MNMR8wL4/M+h95hAqJeaPP6KK3d9Y32LPxfB/tfsHPrpYTIvd6PMJ0RClwt1jMjd+WfCRvl9WUGvFnt+Xh9Q2WXh5LqTHt2t0WaeMzE81wMU5jAUHpND4sm2jNLmos94clY3cOG1b4X4wFNZ7GsA14oxEoXxjgmCDV4h3PshZkTBQgQD7ovP6u9IuwO/3HquvKaTs0v1NaT20egN9g2iYqCFHRwwTHGTpYJ+GXq6MQzzgP2Vz+Dey6shNR44yc585BtBk/b59jufNxyiPALUcpl0UhpdCaUA5qVUpx03qEpvnqCR87gO7DYh02qH75Hy7ESXXfPariVDGkWRjfwHUKZwZCIOqGuh0R89XC8USZ4f4FBrBJ9Avsz0hniOB+04V+mmRGct8ggDiVwAkl2ZWXP1TDgQTpe/8YaANkvCUJ4iwg/cWR
  template:
    metadata:
      name: daddy-github-oauth-secret
      namespace: daddy
