---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daddy-smtp-secret
  namespace: daddy
spec:
  encryptedData:
    SMTP_PASSWORD: AgAOEK2dFuVDYy7GdtugTzZ6a/KB6SGXZtnM6/7k9ED/wN9NPmUl72ytGMN20px9377t5ayxjaPH68pp05FL23sQMU4GQ345Xdk2IW9SYvZ5SShMSMW5vd/vC7kXR9Yq1sn6/Wq7gY2XhVKTPedRiAKg15e053BCwey/D1G5783OvLvr+eNe0OlHhC24ihN3b04Y71k8AXoPB43oUigat2R187abhAyxZ0egTxw86zhdQYyohLZ4P/N4Iy9n7Z5Z91i5ugTTd8nvYA1+63HZ30skzMBtG88u5CiweBizPXiNOYdCc98C2MJiy4mhOlorDLzmoTMvLW9efNfoSkEmWTa4qBmY5bGaGnFJnBuvvH8Yi/YjoSQS7Ojasw3VVPqLei8nAUqRisV2IpHbMfIxAQW/a86Jfsba4soHzeVoUFgy9iCux4HH5ZSAkaL2Y8NdG1W0xNy1lDQTdaa0E2stX3sAn3RZP3Ln1zN6gGxhBEZ443FrkqkGqkNj+rR6DB2hmIU+g2DHtc4TE1hLrfMXuMPcGPbj5beKqu4Ni1p608Wx+Uw4NYIcUb6TNfuEWKH5PydrYA7c6rdb0mAlJBpXQMU4Zj/HX0UAxlALg1EJ+zLl9rlToQykNzGYlyS83W3LoiKXnJf0hdKlQ6Nt8ZHhsdXY37BlVjnmnoR3SJ0GX5rZ2hTo5rrGt0yywt+L+MZpGuhkPPYpJ7iiB0rSo8BxN6u/1ygA
    SMTP_USERNAME: AgCGHJP0Jk0yxRe6AJiBUGQ2L+QJxgPsV1LIdT5LQ2tRHmdlayIIF7ehIfAo5DCn6j4yY2k0tDY0zqEeFJWJu92a4ozYqVdvCDdneX1julKqIv2ItYEHkpGel5I7fv+wzmRGJblcNYzgD+RVNt5hCtpQ5my1lAe1FeDTOoPdwp80Rav5SauAWNPwz1LdObQdmLSrRPnBbRz1MF7Br9nRu8fBcUFfmOaGE3eR0Vnw+5aDF0IJaAs8aRDR4HHEaFCpWaj4h40wt58zxWLffDwi2L13o82mAgvHj9y1nhO8aWT9mtROi1FV0Lu4RZvsaiW5AYwt19LVFL3Q0h0X1IARKjBWfpun5zxzBB2zn3LYWIWIhHrM0QJj6KQZpO9nmg/PyqsVIRzb66CNSARu173JfGyhboA01B2HM7tNnb7cKLk0pXSYL54qz70MU6nJnrQs28qL9jhIL4pKgX9xx0yYSmVWyGjJATQL6T8DcygOjgDkd/oYv/f7HiJYsGFef0Pfz/Z+zbxHw5GljPPo14PRF4mnR8ltPXRfm+ZtbAf2NRFmpn6rLyAQzOZZ2L8mjEqND3KAm26Ys1QHj8X24Zp4IISO9IKRt2jrgZZsgWIO5YxaSrhEEMJ65a5s0DsQFaJYLl6Xfor3I12HidNgzu+GBXkMpz6BkXdLdNUgQZxSgWl5ys5HUDWtGlw59BBmtGMKfo7iMtgetWOYVi97SPmg0/QuDfZLwg==
  template:
    metadata:
      name: daddy-smtp-secret
      namespace: daddy
