---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: daddy-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB55Bqva02oR9hkpin3od9NV0mfxJDdyIr+07aEIbret8eJqgIhfbTo6AHa83470p+4PYSmUHF3KssqmTL5+6lugUz3IsHcpixTEfA2utJDSiapWPsznNtLmrAyKD8LQjXBspBvHUaB3a4BH7R1Ecdz3S2AR8SNpj2pjLJUCzbXAdBaHvyWubn6pyjyRXFYudzmKrr/aSltHn/jk6nfFvlrtzp7eXe20rMaQLxUoIM9XMPa7cq82V4JSAYjn+fi+Git92+n8V/Eaedp7AovOQdMHD1quHz5SeFunqfFcaAzvY0OtYcO29q82+v5mbZL/AF7YXi18DBa4o8A8FZfIG6xB0WDWuG6vOraPhjy58WAUhBQ8N1cP+S4tCw/A9d+XBsW8q+Nq1qzSYzmKrgCZSNjpmHQcPqqlLtijIS/HSJgYpnkQcIZg01UrzgWFfvMCS8mLaU8HUP8acpEu04dzm7WmUkcFmRuA4Hql7/tz1G9JGzVpiSaWgGRcQshjIBbR2AMbfUE385WfnxVcEF1lVH93ZNBNAbE9Sqv/56cfse4Xw9x+tu83eicFvE+8evI9QNM0LdPDo7dI+oPid6H0jUTEUorVI16zpYhjqeieJ1kJ17AonZdldpP6RAX9r/+14dHIFOMYWy6p459qW+PeJjcJRiYhgjiFjIz25khrQFEmNMP9yHL9fiuKlMYl63AjDeVB2QxfOc/j5je2WC5PbCn9mBQLs1wBM2zXhWAFe+FJum1KrYWtpyvGqXrzzKDJsXMwvE39firGAQRmXF3NBPvfN/Txvnj3rbKlMQTOROuGReAI7Vkey5AVA1pcH8X5AqvPiwrmZDrNs8KSFXHGWxHSyGKY/cusNdiNnCPGkJy/y7jT22T0uBjKAJdtu1k7oHAfbQD3HS/qGw++RzBAvOeis/zGTNcqQlxPSoHLkGGLMalQKURP4Ta6A==
  template:
    metadata:
      name: ghcr-credentials
      namespace: daddy-dev
    type: kubernetes.io/dockerconfigjson
