---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daddy-github-oauth-secret
  namespace: daddy-dev
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgBPotHW45gSo00en/4mmIg8MMuAyrR8fL/J/DzF6y6TqNPo79RMUn0HBXU7dtyqA8uErvo458NSjNMiEidC65HsLN3Jg39tYfij8kbwZLovJ8lg/s0ycArbvt7hT/5xg9ZVfd5AqYi4tTd17n7x1wJ/FVl9no9ejEEcHBrnceX96COB8UGmyVct3CdNtRlS/ULFp01YG/vlP6z/ZgGni1dteZerI6yG2TteVDvO5dcilmnoGxl68Ea1z9ZlI1s1CrYoZpHtk9REk1zkc43sg/DM9yDNQfSe3ztMQQ672iWNdt180MFMbf32tAdJGtRLqixXCfPDfIxGyRkeoPpIetkgoVLyd4KoRe2XteSxYg+eDvqx+AYYpln/fCdXp4uZjLLVqahQk8Yv8I3JAFzJkBKIsy5EpirDF49CapSBRqe7dYw39G40/2wNHEUKV4pYufOf6IbMjctMiaRLH9Ml+d+ze4KEf5ZaRfwekWkF0SlszgAiOxLjFs4ti+OkyznNDlXeJgfUa3rEDqRZtG6GUH/IIuzosm0ARW98T1s3j0uBJEzyBCB0lDoCQT4OVUKb5PmzRJX6RHTJ2DSZPpKpgCaocqhj07JfkUqHnBVDgwnj8PWxfmqBi9376GVoPh2GF1+r0v/9TQoqYsGj5eqYrDpvjabhpVHm0Ry2eYbwuWaVIeqPO9mvDN6dsLjCc8nXNxQZ2GomXkJzXkKbaTtQke7aAVrh8Q==
    GITHUB_CLIENT_SECRET: AgBhJKmG/SY7EjdpIVF7yrYjZIjssvmrkCYRUnk3D6VMrq0JYQsOidu2jHKQtGnP+f6MqSlTDREeviH7P/bZ9QHlN4zb5kMWwIQt8Bsyf4el9PjRsxEaH2FhinKfDbZPu1x4yFYUapt/7+OjquHxBCqis+ISPBEisBohSqcYIPUs0Z7rtKp6CncgesUZkb1Lf+UZoLcTuUSDBtUv+Ee28GRbe65/3w4ytaAt8ArN4LzLwXKm7ic29rv2JlcRepZIoX2NEySMyplme7GSiKdHItdsJjtoy4b+bQ+T+mITpHvctcv4BonWhSCYWCDGQUcQZgoBknEFOOuNamTkD7emQA3w1Gemnj093Q7fiZuqe25xXpEvIo6sulga1SDNUSZI+jhDSs+qtvmWHswj0bJYbuZ2FB6L+rMxnUN+Xt121VqzIg7tXv+6ZGRaCmNvU5kvZsCevFlnWgI5PRVY0/Wv+0RiZxUrpbcD/HCN4DQ06do9UJuq1eUJdzpogLbilm1GrKKFd+T3QQEKnx6G5kimGGqgsh4oTUjPW5SUQZga9sSRndxcYyVcbDnPY3DzqylyEG/WpaQH5c6rQYaQWtWvXJRX3RkdSIMvmHI76zhA7gUG8ST+lnpEpYjkWDk2D3n21CcuaEe7+P0PQlgPTWYNx50EIcZp3sR5ZUBkmNsRbkJ7xfjemNb8vsc3rw9HGt82gTGzrmxqdrspIvlx8SNZt4gvLpit3C6Wov9XAy66tSzJkzg/oJuKUMxl
  template:
    metadata:
      name: daddy-github-oauth-secret
      namespace: daddy-dev
