---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daddy-smtp-secret
  namespace: daddy-dev
spec:
  encryptedData:
    SMTP_PASSWORD: AgC3wKr4GhgiBY78YmVQbNPJPopZwGmt2pTZYP0uBgDwIGD92VzwJuBInWuXBwKNOwyg1ygtNLfebZgH4qJIgsZv4Q8vj4v5SnVYGEoS/naSiTtbPxxOVrpW2Wb6lFMK9tiBtVLXNxuRUE8E9G4JmR7+B50rn28WB+/hnHTWHHZ2mAn2xWTmlOmXJNY+2Bl0gVLJqMgnQXO6wut+awR3HMbbfoYYzA4KZF9ruVCScH6n9j9Rk/rk0rpEhfcQLg0lqYsPFEEM2ftnQDmlInA5NIGDILoS8TqRCGyg7ZeZ5yiuvnSLxnqTD2NPdHouDIEBVbTgb/EP5bRiqf6/BjjXBdbRqho0lDbKUYqIVYj/NTbfws5/idCdNiuuLXnDN20nReAiTp4rSfADM77tysTBH5fsED2F9YCNEhXUBJzTFiZK+omFaWmRqWY800s7uSiPYHiZsEsdQk/47b/S2a7jC5NWY9zjds2YVgs3gFGfwXdJa/epZNr53TVIqdJTtht3Qnn+xgWdqiLbtfSD1ZjSM69nDSCKnpwoOW51vC7qPrOjCl66JM4IDtXqRHl2FvPWWTwT2wS+FwcUEvsP1pUCxQMqoxLW3tIIGCs4o8xcx/sqNqi3Wka0QzvfUzWgyhurnRjB5Nni7VHEzrG4glKxygyWiYE0h2DGPB/MquL8GWcOZh9WkjFc2jrUA4lUvxjq57REsWX4EzYNQJ3kuHZUpUjcRvEH
    SMTP_USERNAME: AgApszAkWb9palFBEfhui8DbonCv537p184lpSqzJl4jWR3+KQs1p0b3+xzyTj/dgPjBw+gF0nkrFU8QWD2bjvDYlqMzwAd7b3soIMn87VklCWs3L5RDeP+cE7Jr2cSJbFKswzDTtRx6zCIfKT8Oo8PKtRM8dgmIXBnE0GtKMrgDLI+M1CKNOjZR9q4jDhNMN6VmCMKNjD7br59HoaVwWZUkpURVzJjHd1nAj4Wbc07B0g2Af1eSVdrg1AbKo57pRBrIbQSxvf/RzuwNj3Ebpqy2fgyVM6hccmJFx3k+BEUB6qXEwPsFAc3c3+T9it0Qcm9m7x3TV33lSrK+XqzD7qjY30Y49HvCMg+e6vP/D2OoF//21NoaKZnrvHE2aMPH7I4ScKSYJIMytFzK8JjZcTQXMZd5lJ4oolb48qb94mQaF1Hfvb9zl0QjP0rbnYPhwWfpvXMFSAKkXBYyLDnxmn0Fvx50W0rMfZlJ8ud2fEC95SlJgYhxkfOHmXPCBhbPzpoulvbDxFyUgjvmBf5S0ipoMBPIbsnJXShHk0IKgWlIZFqzruO03G1fP+gNniJjeAynnTPLrRpRkg+YidYhfftSCrVdsAHvEqJXjnbf7pJeeMzuTrWPUIo9cw/cw8EZg7G7q+Tg/ymxZlM2eZjwk6JP88O/TPSuEi0p/enUuxWlcXRgVwY3o7wrfvdSdr/zkoRm1n3iLgR0Ew5lpumoPwo1IHH1hQ==
  template:
    metadata:
      name: daddy-smtp-secret
      namespace: daddy-dev
