apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: daddy
  namespace: argocd
spec:
  description: DADdy platform and application GitOps project
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc
    - namespace: external-dns
      server: https://kubernetes.default.svc
    - namespace: daddy-dev
      server: https://kubernetes.default.svc
    - namespace: daddy
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
