[k8s_single_node]
# Replace with your VM public/private IP
172.26.2.220 ansible_user=debian ansible_port=22

[k8s_single_node:vars]
# Use this if your SSH key is not default (~/.ssh/id_rsa or ~/.ssh/id_ed25519)
# ansible_ssh_private_key_file=~/.ssh/id_ed25519

# Enable this only for bootstrap/testing if host key is unknown
# ansible_ssh_common_args='-o StrictHostKeyChecking=no'
